### ISSUE TITLE
Add number of products at widget

### ISSUE THREAD

**Issue by dimdimich** [swissup/easycatalogimg#1]
Add number of products in widget like https://nordic-led.no/produktkategori/belysning/

**Comment by vovayatsyuk** [comment]
Since magento doesn't provide a performant way to get products count per category I suggest closing this issue. I don't like the idea to create an index table and write a bunch of code for such a small feature. I'd rather recommend using a static block with hardcoded HTML for this purpose.

**Comment by dimdimich** [comment]
Fully agree. That will case perfomance issues.
