### ISSUE TITLE
the click run of the search for images is not working correctly

### ISSUE THREAD

**Issue by ajc200x** [swissup/easycatalogimg#6]
when i click run and search for images, works perfectly but  after i have already ran it once, but found that certain catagories didnt have products for it to add a thumbnail from, i populated the catagory with products and click run again its shows that its added the thumbnail to the backend catagory list, thumbnail bit, but on the frontend, i get no image and , when i inspect its says , 

```
<img src="" srcset=" 1x,  2x" width="200" height="200" alt="Door Closers">
```

I have reindexed and cache flushed, cleaned and deleted all var gen data.

still same result.

**Comment by ajc200x** [comment]
also when you change the thumbnail to another image, via the backend catagory,  it does not change the frontend thumbnail so im stuck with an incorrect thumbnail.  the only current solution is to delete the catagory and let it readd using the automated function

**Comment by ajc200x** [comment]
im using m225 , using your latest version via composer.

**Comment by vovayatsyuk** [comment]
Hi,

1. Is thumbnail image shown in the backend "Category edit" page?
2. If yes, what dimensions it has?

**Comment by ajc200x** [comment]
![github01](https://user-images.githubusercontent.com/18106203/45227839-5f28bf80-b2b9-11e8-947e-b9c38dd8ee00.PNG)

**Comment by ajc200x** [comment]
![github02](https://user-images.githubusercontent.com/18106203/45227889-82536f00-b2b9-11e8-9a69-c67f49dee80f.PNG)

**Comment by ajc200x** [comment]
it is not even using the main image either.

**Comment by ajc200x** [comment]
is there a size limitation of the image?

**Comment by ajc200x** [comment]
ok so it could be a php memory issue?

**Comment by ajc200x** [comment]
i have php set to 3.5gig memory

**Comment by ajc200x** [comment]
or 3500M in my .user and my .php and the root php is also set to 3500M

**Comment by ajc200x** [comment]
i will try with small file size, i will give feedback shortly

**Comment by vovayatsyuk** [comment]
Please, don't change the settings until we know what cause an issue.

Can you just upload some small image and check if it works?

**Comment by ajc200x** [comment]
I have just resized to 600x300 and its still showing the image is the old resolution??

**Comment by ajc200x** [comment]
i cleared cache, that resolved the image size being incorrect,  i clicked remove old image, save, cleared caches, choose the new lower 600x300 image, saved.  cache cleared, and refreshed chrome with a ctrl f5 and still no image being presented. just the place holder.

**Comment by ajc200x** [comment]
![github5](https://user-images.githubusercontent.com/18106203/45229136-f80d0a00-b2bc-11e8-9f7d-204719ac21a5.PNG)

**Comment by ajc200x** [comment]
![github06](https://user-images.githubusercontent.com/18106203/45229188-16730580-b2bd-11e8-9637-8746867444ad.PNG)

no change. after full cache clear

**Comment by ajc200x** [comment]
im using php 7.1 & m225.  on centos vps, 6gig.   3.5gig allocated to sql/php

**Comment by ajc200x** [comment]
also i have disabled the latches category and its still showing the image holder?

**Comment by ajc200x** [comment]
![github6](https://user-images.githubusercontent.com/18106203/45229621-3fe06100-b2be-11e8-9d28-127175208338.PNG)
![github7](https://user-images.githubusercontent.com/18106203/45229625-42db5180-b2be-11e8-9be7-56b85321077b.PNG)

**Comment by ajc200x** [comment]
Your plugin is very good,  just these minor niggles and you could sell this for a ton!!

**Comment by vovayatsyuk** [comment]
Can you also check if these values (thumbnail, enabled) are not overriden at store level? (Use store view switcher at backend "category edit" page)

**Comment by vovayatsyuk** [comment]
Any updates?

**Comment by ajc200x** [comment]
i switched store view mode and ran again and its working, with, the bigger sized pictures too, thank you for the support.

**Comment by vovayatsyuk** [comment]
Great! 

Have a nice day.
